entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
    proxyProtocol:
      insecure: true
    forwardedHeaders:
      insecure: true
  https:
    address: ":443"
    http:
      tls:
        options: intermediate@file
api:
  # insecure: true
  dashboard: true
providers:
  docker:
    exposedbydefault: false
    watch: true
    network: "docker-net"
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: "/path/to/config"
    watch: true
accessLog:
  filePath: "/path/log/access.log"
  format: json
log:
  filePath: "/path/log/traefik.log"
  format: json
  level: DEBUG

