http:
  routers:
    dashboard:
      rule: "Host(`traefik.vvta.cc`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      entrypoints: https
      service: api@internal
      middlewares: auth
      tls: true
  middlewares:
    auth:
      basicauth:
        users:
          - ""
tls:
  certificates:
    - certFile: /root/cert/vvta.cc/cert.pem
      keyFile: /root/cert/vvta.cc/private.key
  stores:
    default:
      defaultCertificate:
        certFile: /root/cert/vvta.cc/cert.pem
        keyFile: /root/cert/vvta.cc/private.key
  options:
    intermediate:
      sniStrict: true
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      curvePreferences:
        - X25519
        - CurveP384
        - CurveP256
      sniStrict: true
      preferServerCipherSuites: true
